version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672

  carts:
    build: ./apps/carts
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
    ports:
      - 8833:3000

  orders:
    build: ./apps/orders
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_PORT=${RABBITMQ_PORT}

  payments:
    build: ./apps/payments
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_PORT=${RABBITMQ_PORT}

  shippings:
    build: ./apps/shippings
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_PORT=${RABBITMQ_PORT}

  mails:
    build:
      context: ./apps/mails
      args:
        - MAIL_HOST=${MAIL_HOST}
        - MAIL_PORT=${MAIL_PORT}
        - MAIL_USERNAME=${MAIL_USERNAME}
        - MAIL_PASSWORD=${MAIL_PASSWORD}
    depends_on:
      - rabbitmq
      SPRING_APPLICATION_JSON: '{
        "spring.rabbitmq.host": "${RABBITMQ_HOST}",
        "spring.rabbitmq.port": "${RABBITMQ_PORT}",

        "spring.mail.host": "${MAIL_HOST}",
        "spring.mail.port": ${MAIL_PORt},
        "spring.mail.username": "${MAIL_USERNAME}",
        "spring.mail.password": "${MAIL_PASSWORD}"
      }'
